---
ID: "b956c08e-595e-4d52-b405-30bce60f4f69"
Parent: "f91a0696-976f-4564-8813-f011225970cc"
Template: "72e58860-ac29-47e1-a1c5-8f9e492db999"
Path: /sitecore/client/Applications/FormsBuilder/Components/Layouts/Actions/IdentifyContact/PageSettings/SettingsForm
SharedFields:
- ID: "30bac824-e6c1-497e-ba09-80529c81c9e6"
  Hint: VisualStyle
  Value: 
- ID: "47ac5c02-a908-46af-9823-c4626e85153c"
  Hint: FieldsLayout
  Value: 
- ID: "a3ea5be2-5a0e-4e72-bb0a-0d0c19615f9e"
  Hint: SectionVisualization
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180606T182727Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "616d499d-478b-4ff1-a126-9bf37bf624a8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180606T191039Z
