---
ID: "333fbb1a-540d-4eff-abd2-4ff689007e44"
Parent: "681b2062-92dd-489e-b5fe-bab03f9eae8c"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/Forms/submitactions/sendmail-dynamicdatasource-1/Page/Section(3)/businessunit/Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201103T084619Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5f21fd3c-ffde-4100-8225-d80260348919"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201103T084619Z
